// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wewaerungcvlakuwuvop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indld2FlcnVuZ2N2bGFrdXd1dm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjI2MjYsImV4cCI6MjA2NTkzODYyNn0.xuyAxLeDWU1s8ROL9NT0QSXk4WxfShy2KUB1Uln9Dm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});